/* ============================================================
   Patlytics Competitive Intelligence — Mock Dataset
   PREVIEW / SAMPLE DATA. This file stands in for the live
   scraping + aggregation pipeline. Company identities, websites,
   LinkedIn URLs, founder names/backgrounds, and the New Market
   Entrants section have been checked against real public sources
   (company sites, LinkedIn, press coverage) where noted below.
   Day-to-day "activity" items (today/this-week feeds, hiring
   counts, marketing items) are still illustrative placeholders
   standing in for the live scraper, unless a field says otherwise.
   Swap this module out for a fetch() to the aggregation API once
   scraping is wired up.
   ============================================================ */

// Fixed "as of" anchor so the demo dataset stays coherent no matter
// when the static preview is actually opened.
const ANCHOR_DATE = "2026-08-25";
const EARLIEST_DATE = "2026-08-04"; // rolling ~21-day archive window

function d(offsetDays) {
  const base = new Date(ANCHOR_DATE + "T12:00:00Z");
  base.setUTCDate(base.getUTCDate() + offsetDays);
  return base.toISOString().slice(0, 10);
}

function siteUrl(domain) {
  return domain ? `https://${domain}` : null;
}

/* ---------------- General Daily Highlights ---------------- */
const HIGHLIGHTS = [
  {
    id: "hl-1",
    date: d(-1),
    priority: "critical",
    category: "Partnership",
    title: "Solve Intelligence and Thomson Reuters partnership now confirmed by both companies",
    summary:
      "Solve Intelligence co-founder Chris Parsonson and the company's own LinkedIn page have publicly confirmed a partnership with Thomson Reuters. Thomson Reuters Ventures is also a confirmed investor in Solve Intelligence (Series A April 2025; increased its stake in Solve's ~$40M Series B, Dec 2025). Exact commercial terms/scope of the partnership are not yet detailed in public sources.",
    whyItMatters:
      "This upgrades what was previously an unconfirmed rumor to a real, company-confirmed relationship. It gives a direct, well-funded competitor an enterprise distribution/investor relationship with exactly the legal-data incumbent whose law-firm and corporate IP-counsel channels Patlytics competes for. Expect Solve to lean on this in enterprise sales conversations.",
    companies: ["Solve Intelligence"],
    source: "Solve Intelligence / Chris Parsonson (LinkedIn)",
    sourceType: "press-release",
    url: "https://www.linkedin.com/posts/chris-parsonson_today-solve-intelligence-is-partnering-with-activity-7497654008715661312-sC4_",
  },
  {
    id: "hl-2",
    date: d(-1),
    priority: "high",
    category: "Funding",
    title: "IPRally closes extended seed round led by European deep-tech investors",
    summary:
      "IPRally raised an extension to its seed round to accelerate its graph-based prior-art search engine and expand go-to-market into the US, its first real push outside the Nordics/EU.",
    whyItMatters:
      "IPRally's search technology is architecturally closest to Patlytics' own approach (embedding + graph retrieval over prior art). A US expansion puts them in direct account contention for the first time.",
    companies: ["IPRally"],
    source: "IPRally newsroom (sample framing — see company site for actual funding history)",
    sourceType: "news",
    url: "https://www.iprally.com/news",
  },
  {
    id: "hl-3",
    date: d(0),
    priority: "high",
    category: "Product",
    title: "PatSnap ships 'Insights Copilot', a conversational layer over its analytics suite",
    summary:
      "PatSnap's new copilot lets users ask natural-language questions over its existing patent analytics and landscape datasets, generating charts and competitive landscape summaries on demand.",
    whyItMatters:
      "This narrows the perceived gap between PatSnap's legacy analytics platform and Patlytics' natural-language-native product. Sales should expect prospects to ask 'how is this different from PatSnap Copilot.'",
    companies: ["PatSnap"],
    source: "PatSnap product blog (sample framing)",
    sourceType: "product",
    url: "https://www.patsnap.com",
  },
  {
    id: "hl-4",
    date: d(0),
    priority: "medium",
    category: "Hiring",
    title: "Clarivate posts VP of AI Product Strategy role reporting into IP leadership",
    summary:
      "The role description references building 'agentic patent research workflows,' signaling Clarivate intends to modernize its IP intelligence platforms rather than sunset them.",
    whyItMatters:
      "A sign the largest incumbent in the space is investing rather than retreating. Worth tracking who fills this seat — likely a strong proxy for Clarivate's AI roadmap and urgency.",
    companies: ["Clarivate (Innography)"],
    source: "LinkedIn Jobs (sample framing)",
    sourceType: "hiring",
    url: "https://clarivate.com/intellectual-property/",
  },
  {
    id: "hl-5",
    date: d(-2),
    priority: "medium",
    category: "Market",
    title: "USPTO updates guidance on AI-assisted inventorship disclosure",
    summary:
      "New guidance clarifies disclosure expectations when generative AI tools are used in the drafting or ideation process for a patent application.",
    whyItMatters:
      "Directly relevant to every AI-drafting vendor in this space, including us. Expect competitor marketing (especially Solve Intelligence, &AI, Fearn, and other AI-drafting tools) to publish compliance positioning within days.",
    companies: ["Industry-wide"],
    source: "USPTO.gov",
    sourceType: "regulatory",
    url: "https://www.uspto.gov/about-us/news-updates",
  },
  {
    id: "hl-6",
    date: d(-3),
    priority: "high",
    category: "Funding",
    title: "Stilta raises $10.5M seed led by a16z for agentic patent litigation AI",
    summary:
      "Stockholm-based Stilta (YC W26), founded by four former McKinsey/QuantumBlack engineers, closed a $10.5M seed round led by Andreessen Horowitz to build source-backed, auditable agentic AI for patent litigation and invalidity work. Already used by multiple AmLaw 100 firms within months of launch.",
    whyItMatters:
      "A very well-capitalized, fast-moving new entrant with immediate BigLaw traction — see the New Market Entrants tab for the full profile.",
    companies: ["Stilta"],
    source: "TechCrunch",
    sourceType: "funding",
    url: "https://techcrunch.com/2026/05/19/legal-tech-announced-stilta-announces-10m-seed-backed-by-yc-and-a16z-months-after-launch/",
  },
  {
    id: "hl-7",
    date: d(-4),
    priority: "low",
    category: "Marketing",
    title: "Anaqua publishes benchmark report on IP department budget allocation",
    summary:
      "Annual survey-based report positions Anaqua as the thought leader on IP operations spend; report is being widely shared by in-house IP counsel on LinkedIn.",
    whyItMatters:
      "Good content-marketing pattern to study, even though Anaqua is only an adjacent competitor. The distribution (in-house counsel sharing organically) is the notable part.",
    companies: ["Anaqua"],
    source: "Anaqua Research (sample framing)",
    sourceType: "marketing",
    url: "https://anaqua.com",
  },
  {
    id: "hl-8",
    date: d(-5),
    priority: "low",
    category: "Webinar",
    title: "LexisNexis Cipher to host webinar on AI patent landscaping for semiconductor portfolios",
    summary:
      "Cipher — acquired by RELX/LexisNexis in 2023 — is running a vertical-specific session aimed at semiconductor IP teams, a segment Patlytics has been expanding into.",
    whyItMatters:
      "Direct audience overlap with our semiconductor vertical push. Consider having someone from the team attend.",
    companies: ["Cipher"],
    source: "Cipher events page (sample framing)",
    sourceType: "webinar",
    url: "https://www.lexisnexisip.com",
  },
  {
    id: "hl-9",
    date: d(-6),
    priority: "high",
    category: "Funding",
    title: "Fearn raises $5.5M seed led by Kindred Ventures for AI-native patent drafting",
    summary:
      "San Francisco-based Fearn, founded by Han Kim (ex-Morrison Foerster, Caltech) and Angela Gao (Caltech PhD, ex-Google Research), raised a $5.5M seed round with participation from a16z speedrun to build a purpose-built patent drafting model targeting a ~20 minute first-draft turnaround.",
    whyItMatters:
      "Direct overlap with Patlytics' and Solve Intelligence's drafting use case, aimed initially at solo inventors and startups rather than enterprise IP departments — worth watching for upmarket movement.",
    companies: ["Fearn"],
    source: "PR Newswire",
    sourceType: "funding",
    url: "https://www.prnewswire.com/news-releases/fearn-raises-5-5-million-seed-to-end-the-two-tier-patent-system-302796012.html",
  },
  {
    id: "hl-10",
    date: "2026-08-18",
    priority: "high",
    category: "Product",
    title: "NLPatent rebrands to Clerq, launches agentic end-to-end patent-work platform",
    summary:
      "NLPatent rebranded to Clerq and unveiled a new agentic AI platform spanning triage assessments through full patentability reports, alongside new partnerships with RPX Corporation and Park IP and a newly hired Director of IP Strategy.",
    whyItMatters:
      "A direct Tier 2 overlap competitor just repositioned itself as an end-to-end agentic patent workflow platform rather than a narrower semantic-search tool — worth re-evaluating how it's pitched against Patlytics going forward.",
    companies: ["NLPatent"],
    source: "IPWatchdog, Law360 Pulse, SiliconANGLE, BetaKit",
    sourceType: "product",
    url: "https://ipwatchdog.com/press/nlpatent-rebrands-to-clerq-unveils-the-next-generation-of-ip-intelligence-built-to-execute-patent-work-end-to-end/",
  },
  {
    id: "hl-11",
    date: "2026-08-13",
    priority: "high",
    category: "Market",
    title: "Questel confirms data breach after vishing attack; ShinyHunters claims ~21M records exfiltrated",
    summary:
      "Questel confirmed attackers accessed part of its Microsoft 365 environment via a voice-phishing (vishing) attack on a Sales SharePoint site. The ShinyHunters group listed Questel SAS on its leak site, claiming roughly 21M records and 147GB of internal files. Questel has notified France's CNIL and filed criminal complaints.",
    whyItMatters:
      "A trust/security signal worth having ready for competitive sales conversations against a Tier 2 overlap competitor — customer data exposure at a rival IP platform is a legitimate differentiator to raise if prospects bring it up.",
    companies: ["Questel"],
    source: "GalaxyWarden, sqmagazine.co.uk, Breachsense",
    sourceType: "news",
    url: "https://www.galaxywarden.com/blog/breach/questel-sas-shinyhunters-2026-08",
  },
  {
    id: "hl-12",
    date: "2026-08-04",
    priority: "medium",
    category: "Partnership",
    title: "Anaqua acquires Unified Patents to add litigation-risk mitigation",
    summary:
      "Anaqua acquired Unified Patents, adding IP-litigation-risk mitigation capabilities to its IP lifecycle-management platform for corporate and law-firm IP departments.",
    whyItMatters:
      "Anaqua is broadening from pure IP operations/docketing into litigation-risk analytics — narrowing the gap with platforms that already combine portfolio management and risk intelligence.",
    companies: ["Anaqua"],
    source: "GlobeNewswire, Law.com",
    sourceType: "press-release",
    url: "https://www.globenewswire.com/news-release/2026/08/04/3338375/0/en/Anaqua-Acquires-Unified-Patents-to-Help-Organizations-Protect-Against-Rising-Intellectual-Property-Litigation-Risk.html",
  },
  {
    id: "hl-13",
    date: "2026-08-20",
    priority: "medium",
    category: "Product",
    title: "Thomson Reuters launches next-generation agentic CoCounsel Legal",
    summary:
      "Thomson Reuters shipped general availability of a 'next generation' agentic CoCounsel Legal (Westlaw Brief Builder, Workspaces, a Word-integrated Drafting Agent, Tabular Analysis), alongside its own proprietary LLM ('Thomson') and an expanded CoCounsel Legal MCP integration with Anthropic's Claude.",
    whyItMatters:
      "Directly relevant given Thomson Reuters' reported partnership push with Solve Intelligence (see above) — TR is visibly accelerating agentic AI investment across its legal/IP stack, reinforcing the distribution threat.",
    companies: ["Casetext (CoCounsel)"],
    source: "Thomson Reuters press release",
    sourceType: "product",
    url: "https://www.thomsonreuters.com/en/press-releases/2026/august/thomson-reuters-launches-next-generation-of-cocounsel-legal-the-ai-ecosystem-built-for-legal-professionals",
  },
  {
    id: "hl-14",
    date: "2026-08-18",
    priority: "low",
    category: "Product",
    title: "Harvey launches 'Harvey II' with persistent cross-app Memory",
    summary:
      "Harvey launched its next-generation platform centered on a persistent 'Memory' feature that learns individual lawyer/client preferences across Harvey, Word, Outlook, and its agents.",
    whyItMatters:
      "Harvey remains the generalist-AI comparison point sales reps hear most often; this keeps its platform story current even though it stays shallow on patent-specific depth.",
    companies: ["Harvey"],
    source: "Artificial Lawyer",
    sourceType: "product",
    url: "https://www.artificiallawyer.com/2026/08/18/next-gen-harvey-ii-launches-with-memory-at-its-core/",
  },
  {
    id: "hl-15",
    date: "2026-08-07",
    priority: "low",
    category: "Funding",
    title: "Harvey reportedly in talks to raise ~$500M at a $15.5B valuation",
    summary:
      "Harvey is reportedly in talks to raise roughly $500M led by Lightspeed at a $15.5B valuation, up from $11B in March 2026; Goldman Sachs Alternatives and J.P. Morgan Growth Equity Partners reportedly invested in late July.",
    whyItMatters:
      "Reported, not yet a confirmed closed round — but continued capital concentration in generalist legal AI keeps Harvey well funded for downmarket/vertical expansion.",
    companies: ["Harvey"],
    source: "SiliconANGLE",
    sourceType: "funding",
    url: "https://siliconangle.com/2026/08/07/legal-ai-startup-harvey-reportedly-raising-500m-15-5b-valuation/",
  },
  {
    id: "hl-16",
    date: "2026-08-13",
    priority: "low",
    category: "Funding",
    title: "Legora reportedly in talks to raise at a $10B valuation",
    summary:
      "Legora (formerly Leya) is reportedly in talks to raise at roughly $10B, nearly double its $5.6B Series D valuation from March 2026.",
    whyItMatters:
      "Another data point on how much capital is flowing into generalist legal AI broadly — worth tracking for budget-competition purposes even though Legora isn't patent-specific.",
    companies: ["Legora"],
    source: "Sifted",
    sourceType: "funding",
    url: "https://sifted.eu/articles/legora-in-talks-to-raise-at-a-10bn-valuation-according-to-reports",
  },
  {
    id: "hl-17",
    date: "2026-08-24",
    priority: "low",
    category: "Funding",
    title: "Newcode raises $13.5M Series A for in-house law-firm AI deployment",
    summary:
      "Newcode (Oslo/Dublin) raised a $13.5M Series A led by OnDean Forward (Relativity founder Andrew Sieja's fund), with participation from Relativity's Rel Labs and The LegalTech Fund, for its configurable AI harness for law-firm document analysis, review, and enterprise search.",
    whyItMatters:
      "A newly funded, general legal-AI entrant — not patent-specific, but worth tracking for budget overlap. See New Market Entrants for the full profile.",
    companies: ["Newcode"],
    source: "Law.com Legaltech News, Artificial Lawyer",
    sourceType: "funding",
    url: "https://www.law.com/legaltechnews/2026/08/24/legal-ai-startup-newcode-announces-135m-series-a-round-with-investment-from-relativity/",
  },
  {
    id: "hl-18",
    date: "2026-08-25",
    priority: "medium",
    category: "Market",
    title: "Robin AI confirmed wound down; engineering team acqui-hired by Microsoft",
    summary:
      "After a planned $50M raise fell through in October 2025, Robin AI laid off roughly a third of staff and sought a buyer. Its managed-services arm was acquired by Scissero in December 2025, and Microsoft absorbed its engineering team in January 2026 to bolster Word's legal-AI features.",
    whyItMatters:
      "Corrects a previously stale 'active adjacent competitor' listing — Robin AI is effectively no longer operating as an independent company. Verified today via multiple independent outlets.",
    companies: ["Robin AI"],
    source: "Legal Cheek, Artificial Lawyer, nonbillable.co.uk",
    sourceType: "news",
    url: "https://www.legalcheek.com/2025/10/uk-lawtech-business-seeks-buyer-following-38-million-fundraising-setback/",
  },
  {
    id: "hl-19",
    date: "2026-08-25",
    priority: "low",
    category: "Market",
    title: "IPwe confirmed defunct following 2024 bankruptcy liquidation",
    summary:
      "IPwe filed for Chapter 11 bankruptcy in Delaware in January 2024 and later converted to Chapter 7 liquidation after its bankruptcy financing fell through. The company is no longer operating.",
    whyItMatters:
      "Corrects a previously stale 'active adjacent competitor' listing. Verified today via Law360's court coverage.",
    companies: ["IPwe"],
    source: "Law360",
    sourceType: "news",
    url: "https://www.law360.com/ip/articles/1810349/ipwe-seeks-ch-7-liquidation-after-ch-11-financing-loss",
  },
  {
    id: "hl-20",
    date: d(0),
    priority: "high",
    category: "Product",
    title: "Google Cloud launches \"Gemini Enterprise for Legal\"",
    summary:
      "Google Cloud unveiled a purpose-built, industry-specific version of Gemini Enterprise for law firms and corporate legal departments, in preview, with legal-specific \"skills\" (citation verification, contract lifecycle management, brief drafting, DSAR execution, regulation monitoring) and connectors into existing DMS/e-discovery/research systems. Cleary Gottlieb, Freshfields, Weil, and Williams & Connolly are named launch firms.",
    whyItMatters:
      "A hyperscaler entering legal AI natively at the platform level — not as a point solution — is a structural signal for every legal/IP AI vendor, including patent-specific tools that may eventually need to interoperate with (or compete against) Gemini Enterprise's legal skills.",
    companies: ["Industry-wide"],
    source: "Artificial Lawyer, Law.com (American Lawyer / Legaltech News)",
    sourceType: "product",
    url: "https://www.artificiallawyer.com/2026/08/25/google-launches-gemini-enterprise-for-legal/",
  },
];

/* ---------------- Competitors ---------------- */
// rank = correlation/threat ranking used to order sidebar tabs (1 = highest)
// website / linkedin URLs below have been verified against real company
// sites and LinkedIn company pages. Founder bios are verified only where
// explicitly noted; otherwise they are placeholders pending the scraping
// pipeline. Day-to-day activity/hiring/marketing items remain illustrative.
const COMPETITORS = [
  {
    id: "solve-intelligence",
    name: "Solve Intelligence",
    rank: 2,
    tier: "Tier 1 — Direct Competitor",
    initials: "SI",
    tagline: "AI copilot for patent drafting, prosecution, and portfolio management.",
    description:
      "Solve Intelligence builds an AI-native workspace for patent attorneys and agents, covering claim drafting, office-action response drafting, and prosecution docketing. Its core wedge is generative drafting assistance embedded directly into attorneys' existing workflows, and it has moved quickly from a drafting tool into a broader prosecution platform, including the 2026 acquisition of ClaimWise to deepen European litigation/opposition coverage.",
    employeeCount: "~90 (est.)",
    founded: "2023",
    hq: "San Francisco, CA",
    website: "solveintelligence.com",
    websiteUrl: siteUrl("solveintelligence.com"),
    careersUrl: siteUrl("solveintelligence.com") + "/careers",
    linkedin: "https://uk.linkedin.com/company/solve-intelligence",
    founders: [
      {
        name: "Dr. Chris Parsonson",
        title: "Co-Founder & CEO",
        note: "MRes, University of Cambridge; MEng, Imperial College London; PhD in machine learning, UCL. Previously at The Alan Turing Institute, InstaDeep, and Dyson. (Verified via press coverage.)",
      },
      {
        name: "Dr. Sanj Ahilan",
        title: "Co-Founder",
        note: "MSci in Physics, University of Cambridge; PhD in machine learning, UCL. Previously at Magic Carpet AI and Huawei Technologies. (Verified via press coverage.)",
      },
      {
        name: "Angus Parsonson",
        title: "Co-Founder & CTO",
        note: "Background details pending further verification.",
      },
    ],
    todayActivity: [
      {
        time: "9:14 AM",
        tag: "Partnership",
        title: "Thomson Reuters partnership confirmed by both companies",
        body: "Solve Intelligence and Thomson Reuters have both publicly confirmed a partnership (founder + company LinkedIn posts). Thomson Reuters Ventures is also a confirmed investor. See General Highlights — exact commercial terms/scope are not yet publicly detailed.",
        url: "https://www.linkedin.com/posts/chris-parsonson_today-solve-intelligence-is-partnering-with-activity-7497654008715661312-sC4_",
      },
    ],
    weekActivity: [
      {
        date: d(-3),
        tag: "Product",
        title: "Shipped office-action response drafting v2",
        body: "Rolled out an updated model for drafting office-action responses with claim-amendment suggestions inline.",
        url: siteUrl("solveintelligence.com"),
      },
      {
        date: d(-4),
        tag: "Content",
        title: "Published benchmark comparing drafting speed vs. traditional workflows",
        body: "Marketing report claiming ~40% reduction in first-draft turnaround time, widely shared by patent attorneys on LinkedIn.",
        url: siteUrl("solveintelligence.com"),
      },
      {
        date: d(-6),
        tag: "Hiring",
        title: "Opened first Solutions Engineering role",
        body: "Signals a push toward more hands-on enterprise/firm onboarding rather than pure self-serve.",
        url: siteUrl("solveintelligence.com") + "/careers",
      },
    ],
    hiring: {
      openRoles: 14,
      newRolesToday: [
        { title: "Enterprise Account Executive", dept: "Sales", location: "Remote (US)" },
      ],
      recentHires: [
        { name: "Sample Hire A", role: "Head of Partnerships", from: "Prior role: BigLaw-adjacent legal tech (sample)", date: d(-2) },
        { name: "Sample Hire B", role: "Senior ML Engineer", from: "Prior role: large-model applied research (sample)", date: d(-5) },
      ],
      topRoles: [
        { title: "Software Engineer, Full-Stack", count: 4 },
        { title: "Enterprise Account Executive", count: 3 },
        { title: "Patent Attorney (In-House SME)", count: 2 },
      ],
    },
    marketing: [
      {
        title: "“Drafting at the speed of thought” LinkedIn campaign",
        body: "Short-form video series featuring attorneys narrating drafting workflows in real time; strong engagement from IP counsel audience.",
        channel: "LinkedIn",
        date: d(-2),
        url: "https://uk.linkedin.com/company/solve-intelligence",
      },
      {
        title: "Sponsored AIPLA newsletter placement",
        body: "Recurring sponsor slot in a widely-read patent bar newsletter, reinforcing top-of-funnel brand presence with attorneys.",
        channel: "Newsletter",
        date: d(-6),
        url: siteUrl("solveintelligence.com"),
      },
    ],
  },
  {
    id: "patsnap",
    name: "PatSnap",
    rank: 3,
    tier: "Tier 1 — Direct Competitor",
    initials: "PS",
    tagline: "Global patent analytics and IP intelligence platform.",
    description:
      "PatSnap is an established IP intelligence platform offering patent search, analytics, landscaping, and competitive monitoring across a large global dataset. It has recently pushed into generative AI features layered on top of its existing analytics core, competing for the same 'ask questions of your patent data' use case Patlytics targets natively.",
    employeeCount: "~800 (est.)",
    founded: "2007",
    hq: "Singapore / London",
    website: "patsnap.com",
    websiteUrl: siteUrl("patsnap.com"),
    careersUrl: siteUrl("patsnap.com") + "/careers",
    linkedin: "https://www.linkedin.com/company/patsnap",
    founders: [
      {
        name: "Sample Founder Profile",
        title: "Co-Founder & CEO",
        note: "Placeholder — bio pending verification via scraping pipeline.",
      },
    ],
    todayActivity: [
      {
        time: "7:40 AM",
        tag: "Product",
        title: "Launched “Insights Copilot” conversational analytics layer",
        body: "New natural-language query layer sits on top of PatSnap's existing landscape and analytics datasets. See General Highlights.",
        url: siteUrl("patsnap.com"),
      },
    ],
    weekActivity: [
      {
        date: d(-1),
        tag: "Content",
        title: "Published R&D patent-landscape analysis on direct air capture",
        body: "PatSnap Research published \"Direct Air Capture Energy Integration Patents: Leaders & Filing Trends 2026,\" analyzing 732 patent records across 100 companies.",
        url: "https://www.patsnap.com/resources/blog/rd-blog/direct-air-capture-energy-integration-patent-data/",
      },
      {
        date: d(-2),
        tag: "Sales",
        title: "Announced renewal of a large pharma enterprise account",
        body: "Case study published highlighting multi-year renewal with a top-20 pharma IP department.",
        url: siteUrl("patsnap.com"),
      },
      {
        date: d(-5),
        tag: "Event",
        title: "Exhibited at INTA Annual Meeting",
        body: "Large booth presence with live product demos of the new copilot feature.",
        url: siteUrl("patsnap.com"),
      },
    ],
    hiring: {
      openRoles: 37,
      newRolesToday: [
        { title: "Solutions Consultant, EMEA", dept: "Customer Success", location: "London, UK" },
        { title: "Data Engineer", dept: "Engineering", location: "Singapore" },
      ],
      recentHires: [
        { name: "Sample Hire C", role: "VP, Product (AI)", from: "Prior role: enterprise SaaS analytics (sample)", date: d(-3) },
      ],
      topRoles: [
        { title: "Account Executive", count: 9 },
        { title: "Data/ML Engineer", count: 6 },
        { title: "Customer Success Manager", count: 5 },
      ],
    },
    marketing: [
      {
        title: "“State of Patent Analytics 2026” gated report",
        body: "Large lead-gen content push distributed via LinkedIn ads targeting in-house IP counsel and R&D leaders.",
        channel: "LinkedIn Ads",
        date: d(-1),
        url: siteUrl("patsnap.com"),
      },
    ],
  },
  {
    id: "iprally",
    name: "IPRally",
    rank: 5,
    tier: "Tier 1 — Direct Competitor",
    initials: "IR",
    tagline: "AI-native graph search engine for prior art and freedom-to-operate.",
    description:
      "IPRally built a graph-embedding based search engine specifically for prior-art and freedom-to-operate search, arguing traditional keyword/classification search misses semantically relevant results. Historically focused on the Nordics/EU market, now expanding into the US.",
    employeeCount: "~45 (est.)",
    founded: "2018",
    hq: "Helsinki, Finland",
    website: "iprally.com",
    websiteUrl: siteUrl("iprally.com"),
    careersUrl: siteUrl("iprally.com") + "/careers",
    linkedin: "https://fi.linkedin.com/company/iprally",
    founders: [
      {
        name: "Sample Founder Profile",
        title: "Co-Founder & CTO",
        note: "Placeholder — technical background pending verification via scraping pipeline.",
      },
    ],
    todayActivity: [],
    weekActivity: [
      {
        date: d(-1),
        tag: "Funding",
        title: "Closed extended seed round for US expansion",
        body: "Round earmarked for opening a US commercial presence and localized go-to-market. See General Highlights.",
        url: siteUrl("iprally.com") + "/news",
      },
      {
        date: d(-4),
        tag: "Hiring",
        title: "Opened first US-based sales role",
        body: "First indication of direct US account coverage rather than partner-led sales.",
        url: siteUrl("iprally.com") + "/careers",
      },
    ],
    hiring: {
      openRoles: 8,
      newRolesToday: [],
      recentHires: [
        { name: "Sample Hire D", role: "Head of US Expansion", from: "Prior role: EU-to-US SaaS GTM (sample)", date: d(-4) },
      ],
      topRoles: [
        { title: "Search/ML Research Engineer", count: 3 },
        { title: "Account Executive (US)", count: 2 },
      ],
    },
    marketing: [
      {
        title: "Technical blog: “Why embeddings beat classification codes”",
        body: "Deep technical post aimed at patent search professionals, positioning against classification-code-based search (a subtle jab at legacy platforms).",
        channel: "Company Blog",
        date: d(-3),
        url: siteUrl("iprally.com"),
      },
    ],
  },
  {
    id: "clarivate-innography",
    name: "Clarivate (Innography)",
    rank: 10,
    tier: "Tier 2 — Strong Overlap",
    initials: "CL",
    tagline: "Large incumbent IP intelligence suite under the Clarivate umbrella.",
    description:
      "Clarivate's IP Solutions division (which absorbed the Innography patent-analytics platform) is a long-standing patent analytics and portfolio management suite serving large enterprise and law-firm accounts, now unified under the 'IPOne' AI-enabled IP intelligence ecosystem. Recent signals suggest Clarivate is investing in AI-native features rather than treating the platform as legacy.",
    employeeCount: "Clarivate: ~9,000 (IP Solutions unit est. ~150)",
    founded: "Innography: 2006 (acquired by Clarivate 2021)",
    hq: "Philadelphia, PA (Clarivate global HQ: London, UK)",
    website: "clarivate.com/intellectual-property",
    websiteUrl: "https://clarivate.com/intellectual-property/",
    careersUrl: "https://clarivate.com/careers/",
    linkedin: "https://www.linkedin.com/company/clarivate",
    founders: [
      {
        name: "N/A — division of public company",
        title: "Business unit leadership",
        note: "Operates as a business unit inside Clarivate (NYSE: CLVT); tracked at leadership/org level rather than founder level.",
      },
    ],
    todayActivity: [
      {
        time: "11:02 AM",
        tag: "Hiring",
        title: "Posted VP of AI Product Strategy role",
        body: "Role reports into IP Solutions leadership and references 'agentic patent research workflows.' See General Highlights.",
        url: "https://clarivate.com/careers/",
      },
    ],
    weekActivity: [
      {
        date: d(-3),
        tag: "Corporate",
        title: "Clarivate earnings call referenced AI investment across IP segment",
        body: "Leadership called out AI feature velocity in the IP Solutions segment as a retention priority for FY26.",
        url: "https://clarivate.com/intellectual-property/",
      },
    ],
    hiring: {
      openRoles: 22,
      newRolesToday: [
        { title: "VP, AI Product Strategy", dept: "Product", location: "Remote (US)" },
      ],
      recentHires: [],
      topRoles: [
        { title: "Product Manager, AI", count: 3 },
        { title: "Enterprise Account Manager", count: 5 },
      ],
    },
    marketing: [
      {
        title: "Webinar series: “Modernizing Legacy IP Data Infrastructure”",
        body: "Multi-part webinar aimed at retaining large legacy accounts considering newer AI-native tools.",
        channel: "Webinar",
        date: d(-5),
        url: "https://clarivate.com/intellectual-property/",
      },
    ],
  },
  {
    id: "anaqua",
    name: "Anaqua",
    rank: 11,
    tier: "Tier 2 — Strong Overlap",
    initials: "AQ",
    tagline: "End-to-end IP management software for corporate and law-firm IP departments.",
    description:
      "Anaqua provides IP lifecycle management software — docketing, portfolio management, renewals, and increasingly analytics — for corporate IP departments and law firms. Overlaps with Patlytics primarily where IP operations and analytics intersect rather than on core AI search/drafting.",
    employeeCount: "~700 (est.)",
    founded: "2004",
    hq: "Boston, MA",
    website: "anaqua.com",
    websiteUrl: siteUrl("anaqua.com"),
    careersUrl: siteUrl("anaqua.com") + "/careers",
    linkedin: "https://www.linkedin.com/company/anaqua",
    founders: [
      {
        name: "Sample Founder Profile",
        title: "Founder & Executive Chairman",
        note: "Placeholder — bio pending verification via scraping pipeline.",
      },
    ],
    todayActivity: [
      {
        time: "12:00 PM ET",
        tag: "Marketing",
        title: "Hosting live webinar: 'AI for Lean IP Teams'",
        body: "Live session on helping lean IP teams do more with less while empowering junior staff using AI.",
        url: "https://ipwatchdog.com/event/webinar-anaqua-2026-08-25-ai-for-lean-ip-teams/",
      },
    ],
    weekActivity: [
      {
        date: "2026-08-04",
        tag: "Corporate",
        title: "Acquired Unified Patents",
        body: "Anaqua acquired Unified Patents to add IP-litigation-risk mitigation capabilities to its lifecycle-management platform. See General Highlights.",
        url: "https://www.globenewswire.com/news-release/2026/08/04/3338375/0/en/Anaqua-Acquires-Unified-Patents-to-Help-Organizations-Protect-Against-Rising-Intellectual-Property-Litigation-Risk.html",
      },
      {
        date: d(-4),
        tag: "Marketing",
        title: "Published annual IP department budget benchmark report",
        body: "Survey-based report widely shared organically by in-house IP counsel on LinkedIn. See General Highlights.",
        url: siteUrl("anaqua.com"),
      },
    ],
    hiring: {
      openRoles: 19,
      newRolesToday: [],
      recentHires: [
        { name: "Sample Hire E", role: "Director, Analytics Product", from: "Prior role: legal-ops analytics (sample)", date: d(-6) },
      ],
      topRoles: [
        { title: "Implementation Consultant", count: 6 },
        { title: "Account Manager", count: 4 },
      ],
    },
    marketing: [
      {
        title: "“IP Ops Benchmark 2026” report",
        body: "Annual survey report driving strong organic LinkedIn distribution among in-house counsel.",
        channel: "Content / Organic Social",
        date: d(-4),
        url: siteUrl("anaqua.com"),
      },
    ],
  },
  {
    id: "lexisnexis-ip",
    name: "LexisNexis IP Solutions",
    rank: 10.5,
    tier: "Tier 2 — Strong Overlap",
    initials: "LN",
    tagline: "PatentSight + IPlytics — patent portfolio value and SEP/standards analytics.",
    description:
      "LexisNexis' IP Solutions division (part of RELX) offers PatentSight for patent portfolio valuation/benchmarking and IPlytics (acquired November 2022) for standard-essential-patent (SEP) and standards analytics — a distinct product line from LexisNexis Cipher (tracked separately in this dashboard), giving the RELX/LexisNexis umbrella multiple overlapping footholds in patent analytics.",
    employeeCount: "RELX: ~10,000+ (IP Solutions unit size not separately disclosed)",
    founded: "PatentSight: 2013 (acquired by LexisNexis 2019); IPlytics: acquired by LexisNexis November 2022",
    hq: "Darmstadt, Germany (PatentSight); Berlin, Germany (IPlytics); LexisNexis IP global HQ: Dayton, OH",
    website: "lexisnexisip.com",
    websiteUrl: siteUrl("lexisnexisip.com"),
    careersUrl: "https://www.lexisnexis.com/en-us/careers.page",
    linkedin: "https://www.linkedin.com/company/lexisnexisip",
    founders: [
      {
        name: "N/A — division of public company (RELX)",
        title: "Business unit leadership",
        note: "PatentSight and IPlytics were independent companies before being acquired by LexisNexis; original founder details tracked separately from LexisNexis' own leadership.",
      },
    ],
    todayActivity: [],
    weekActivity: [
      {
        date: d(-2),
        tag: "Product",
        title: "Combined patent datasets and software solutions under one platform",
        body: "LexisNexis IP Solutions announced combining its best-in-class patent datasets and software into a unified analytics offering.",
        url: "https://www.lexisnexisip.com/resources/lexisnexis-combines-best-in-class-patent-datasets-and-software-solutions-boosting-innovation-analytics-to-a-new-level/",
      },
    ],
    hiring: {
      openRoles: null,
      newRolesToday: [],
      recentHires: [],
      topRoles: [],
    },
    marketing: [],
  },
  {
    id: "cipher",
    name: "Cipher (a LexisNexis company)",
    rank: 22,
    tier: "Tier 3 — Adjacent",
    initials: "CI",
    tagline: "AI-driven IP intelligence and visualization for technical due diligence.",
    description:
      "Cipher focuses on applied-science-heavy patent landscaping and visualization, often used for technical due diligence and R&D strategy rather than pure legal workflows. Cipher was acquired by RELX (LexisNexis' parent company) in 2023 and now operates as LexisNexis Cipher, giving it access to LexisNexis' broader IP data and distribution.",
    employeeCount: "~120 (est.)",
    founded: "2013 (acquired by RELX/LexisNexis, 2023)",
    hq: "Paris, France",
    website: "lexisnexisip.com",
    websiteUrl: siteUrl("lexisnexisip.com"),
    careersUrl: "https://www.lexisnexis.com/en-us/careers.page",
    linkedin: "https://www.linkedin.com/company/cipher-strategicpatentintelligence",
    founders: [
      {
        name: "Sample Founder Profile",
        title: "Co-Founder (pre-acquisition)",
        note: "Placeholder — bio pending verification via scraping pipeline.",
      },
    ],
    todayActivity: [],
    weekActivity: [
      {
        date: "2026-08-18",
        tag: "Webinar",
        title: "Hosted webinar: AI-Powered Patent Landscaping",
        body: "Live session on AI-driven landscaping methodology for patent portfolios. See the Webinars tab.",
        url: "https://ipwatchdog.com/event/webinar-lexisnexis-2026-08-18-ai-powered-patent-landscaping/",
      },
    ],
    hiring: {
      openRoles: 6,
      newRolesToday: [],
      recentHires: [],
      topRoles: [
        { title: "Patent Analyst (Semiconductor)", count: 2 },
        { title: "Data Scientist", count: 2 },
      ],
    },
    marketing: [
      {
        title: "AI-Powered Patent Landscaping webinar",
        body: "Live webinar on AI-driven landscaping methodology for patent portfolios, listed via IPWatchdog's events partner program.",
        channel: "Webinar",
        date: "2026-08-18",
        url: "https://ipwatchdog.com/event/webinar-lexisnexis-2026-08-18-ai-powered-patent-landscaping/",
      },
    ],
  },
  {
    id: "ktmine",
    name: "ktMINE",
    rank: 23,
    tier: "Tier 3 — Adjacent",
    initials: "KT",
    tagline: "IP and royalty rate benchmarking data intelligence.",
    description:
      "ktMINE specializes in licensing and royalty-rate benchmarking data alongside patent data services, serving valuation, licensing, and transfer-pricing use cases. Overlap with Patlytics is narrow but relevant for valuation-adjacent enterprise deals.",
    employeeCount: "~90 (est.)",
    founded: "2010",
    hq: "Chicago, IL",
    website: "ktmine.com",
    websiteUrl: siteUrl("ktmine.com"),
    careersUrl: siteUrl("ktmine.com") + "/careers",
    linkedin: "https://www.linkedin.com/company/ktmine",
    founders: [
      {
        name: "Sample Founder Profile",
        title: "Founder & CEO",
        note: "Placeholder — bio pending verification via scraping pipeline.",
      },
    ],
    todayActivity: [],
    weekActivity: [],
    hiring: {
      openRoles: 4,
      newRolesToday: [],
      recentHires: [],
      topRoles: [{ title: "Licensing Data Analyst", count: 2 }],
    },
    marketing: [],
  },
  {
    id: "ipwe",
    name: "IPwe",
    rank: 24,
    tier: "Tier 3 — Adjacent",
    initials: "IW",
    tagline: "AI and blockchain-based patent data and marketplace platform. DEFUNCT — see note.",
    description:
      "IPwe combined AI-driven patent data normalization with a blockchain-based patent registry and marketplace concept, targeting patent monetization and portfolio valuation use cases. IPwe filed for Chapter 11 bankruptcy in Delaware in January 2024 and later converted to Chapter 7 liquidation after its bankruptcy financing fell through — the company is confirmed no longer operating (verified 2026-08-25, see General Highlights).",
    employeeCount: "0 — company liquidated (Chapter 7, 2024)",
    founded: "2017 (ceased operations 2024)",
    hq: "New York, NY",
    website: "ipwe.com",
    websiteUrl: siteUrl("ipwe.com"),
    careersUrl: siteUrl("ipwe.com") + "/careers",
    linkedin: "https://www.linkedin.com/company/ipwe-com",
    founders: [
      {
        name: "Sample Founder Profile",
        title: "Co-Founder & CEO",
        note: "Placeholder — bio pending verification via scraping pipeline.",
      },
    ],
    todayActivity: [],
    weekActivity: [],
    hiring: {
      openRoles: 3,
      newRolesToday: [],
      recentHires: [],
      topRoles: [{ title: "Business Development Manager", count: 1 }],
    },
    marketing: [],
  },
];

// Additional competitors surfaced via (a) Patlytics' own internal Notion
// "Competitor Analysis" workspace — DeepIP, Junior, Ankar AI, Edge, and
// Patented.ai are all explicitly tracked there — and (b) a broader,
// individually-verified sweep of the AI-patent and AI-legal landscape.
// Website/LinkedIn URLs are verified real destinations. Day-to-day
// activity, hiring counts, and founder bios have not been scraped yet for
// these, so those fields are intentionally left as "not yet verified"
// rather than guessed.
function stubCompetitor({
  id, name, rank, tier, initials, tagline, description, website, linkedin,
  employeeCount, founded, hq, founders, todayActivity, weekActivity, hiring, marketing,
}) {
  return {
    id,
    name,
    rank,
    tier,
    initials,
    tagline,
    description,
    employeeCount: employeeCount || "Not yet verified — pending scrape",
    founded: founded || "Not yet verified",
    hq: hq || "Not yet verified — pending scrape",
    website,
    websiteUrl: siteUrl(website),
    careersUrl: siteUrl(website) + "/careers",
    linkedin,
    founders: founders || [
      { name: "Not yet verified", title: "Founder/CEO", note: "Placeholder — pending verification via scraping pipeline." },
    ],
    todayActivity: todayActivity || [],
    weekActivity: weekActivity || [],
    hiring: hiring || { openRoles: null, newRolesToday: [], recentHires: [], topRoles: [] },
    marketing: marketing || [],
  };
}

COMPETITORS.push(
  stubCompetitor({
    id: "deepip",
    name: "DeepIP",
    rank: 1,
    tier: "Tier 1 — Direct Competitor",
    initials: "DI",
    tagline: "AI patent drafting and prosecution platform.",
    description: "Repeatedly identified inside Patlytics' own competitive-analysis tracking as the closest direct competitor — an AI drafting and prosecution platform with significant product overlap. Highest-priority watch-list entry. Acquired German AI patent-drafting tool PatentMaker in June 2026 to build out European coverage, and exhibited at PATINFO 2026 (Ilmenau) on prior art search, Markush drafting, and office-action response.",
        employeeCount: "~51-200 per LinkedIn; other trackers cite 45-71",
    founded: "2023",
    hq: "Brooklyn, NY (also maintains a Paris office)",
    founders: [
      { name: "François-Xavier (FX) Leduc", title: "Co-Founder & CEO", note: "Previously co-founded Kili Technology (data-labeling/AI); DeepIP spun out of that team." },
      { name: "Édouard d'Archimbaud", title: "Co-Founder & CTO", note: "Previously co-founded Kili Technology alongside Leduc." },
    ],
    website: "deepip.ai",
    linkedin: "https://www.linkedin.com/company/deep-ip",
  }),
  stubCompetitor({
    id: "junior",
    name: "Junior",
    rank: 6,
    tier: "Tier 1 — Direct Competitor",
    initials: "JR",
    tagline: "AI-native patent drafting inside Microsoft Word.",
    description: "Atlanta-based Junior builds AI-native patent drafting tooling that works directly inside Microsoft Word, targeting the same drafting workflow Patlytics and Solve Intelligence compete for.",
        employeeCount: "11-50 per LinkedIn",
    founded: "2025 per LinkedIn (conflicts with earlier press coverage describing an active Atlanta-based startup — not fully reconciled)",
    hq: "Mountain View, CA per LinkedIn; press coverage (Hypepotamus) describes it as Atlanta-based — conflicting sources, not resolved",
    founders: [
      { name: "Yuri Eliezer", title: "Co-Founder & CEO", note: "Also a founding patent attorney at Founders Legal; JD, Georgia State University College of Law; undergrad at Georgia Tech." },
    ],
    website: "junior.law",
    linkedin: "https://www.linkedin.com/company/junior-ai-drafting",
  }),
  stubCompetitor({
    id: "ankar-ai",
    name: "Ankar AI",
    rank: 7,
    tier: "Tier 1 — Direct Competitor",
    initials: "AN",
    tagline: "AI operating system for patent prosecution and portfolio management.",
    description: "UK-based Ankar AI is building an AI-driven operating system spanning patent prosecution and portfolio management workflows. Raised a $20M Series A led by Atomico in December 2025 (total raised ~$24M).",
        employeeCount: "Not consistently verified — estimates range 18-42 across sources; LinkedIn shows 11-50",
    founded: "2024 (per seed-round coverage)",
    hq: "London, UK",
    founders: [
      { name: "Tamar Gomez", title: "CEO", note: "Previously worked at Palantir." },
      { name: "Wiem Gharbi", title: "CTO", note: "Previously worked on ML applications at Palantir." },
    ],
    website: "ankar.ai",
    linkedin: "https://www.linkedin.com/company/ankar-ai",
    weekActivity: [
      {
        date: "2026-08-25",
        tag: "Hiring",
        title: "Actively hiring across product, sales, and patent engineering",
        body: "Live openings observed today via public job postings, including Senior Product Engineer, Product Manager, Account Executive, Patent Product Engineer, and a Founder's Associate (Growth, Hiring & Ops) role — consistent with post-Series A scale-up.",
        url: "https://uk.linkedin.com/jobs/view/senior-product-engineer-at-ankar-4411350945",
      },
    ],
    marketing: [
      {
        title: "Hosting webinar: 'AI in Patent Practice — Change Management for Successful Adoption'",
        body: "Upcoming live webinar (Sept 10, 2026) aimed at IP teams navigating AI adoption change management. See the Webinars tab.",
        channel: "Webinar",
        date: "2026-08-25",
        url: "https://ipwatchdog.com/ankar-ai-september-10-2026/",
      },
    ],
  }),
  stubCompetitor({
    id: "edge",
    name: "Edge",
    rank: 8,
    tier: "Tier 1 — Direct Competitor",
    initials: "ED",
    tagline: "AI patent drafting (\"Ingenia\") and trademark clearance.",
    description: "Edge offers AI patent drafting under its \"Ingenia\" product alongside trademark-clearance tooling, giving it a foothold in both patent and trademark AI workflows. Launched Certus, described as \"the world's first AI agent for trademark law\" (automated clearance search and filing), in April 2026.",
        employeeCount: "LinkedIn lists 2-10 — likely stale given $37.4M raised across 5 rounds; not independently verified",
    founded: "2020",
    hq: "San Francisco, CA",
    founders: [
      { name: "Evan Zimmerman", title: "Co-Founder & CEO", note: "JD, UC Berkeley Law; named to Forbes 30 Under 30 (2023)." },
      { name: "Len Boyette", title: "Co-Founder", note: "Background in software engineering, cybersecurity, and cloud infrastructure." },
    ],
    website: "withedge.com",
    linkedin: "https://www.linkedin.com/company/workwithedge",
  }),
  stubCompetitor({
    id: "patented-ai",
    name: "Patented.ai",
    rank: 9,
    tier: "Tier 1 — Direct Competitor",
    initials: "PA",
    tagline: "AI infringement detection via claim-to-code mapping.",
    description: "Patented.ai focuses on infringement analysis, mapping patent claims directly to product code/implementation to generate infringement evidence — tracked with its own dedicated page in Patlytics' internal competitor analysis. Recent release notes describe a \"Parallel AI Processor\" (claimed 50-75x speed-up via parallel claim-term extraction), a \"Secure Viewer\" with proactive result notifications and PDF export, and workspace-based team collaboration with corporate auth (exact publish date not stated on the release-notes page).",
        employeeCount: "2-10 per LinkedIn",
    founded: "2023",
    hq: "Santa Monica, CA per company site (LinkedIn lists Delaware, likely the incorporation state)",
    founders: [
      { name: "Wayne Chang", title: "Founder & CEO", note: "Previously co-founded Crashlytics (mobile crash-reporting; acquired by Twitter, 2013); named to Forbes' Top 50 Angel Investors." },
    ],
    website: "patented.ai",
    linkedin: "https://www.linkedin.com/company/patented",
  }),
  stubCompetitor({
    id: "xlscout",
    name: "XLSCOUT",
    rank: 4,
    tier: "Tier 1 — Direct Competitor",
    initials: "XL",
    tagline: "AI patent search, drafting-assist, and monetization platform.",
    description: "XLSCOUT offers AI-driven patent search, drafting assistance, and monetization/valuation tooling. Named directly in a real Patlytics customer call as running a parallel evaluation trial alongside PatSnap against Patlytics. Background partnerships/collaborations referenced in press include AL FAHIM Group, a Hugging Face \"Para Embed\" model collaboration, and a MaRS Innovation Hub tie-up (exact dates not independently pinned down in this pass).",
        employeeCount: "~51-200 per LinkedIn",
    founded: "Not fully verified — legal entity incorporated 2012 in Chandigarh, India; platform reportedly relaunched under the XLSCOUT name around 2020",
    hq: "Toronto, Ontario, Canada (primary); also maintains a Chandigarh, India office",
    founders: [
      { name: "Jitin Talwar", title: "Co-Founder", note: "Background details not independently verified." },
      { name: "Komal Sharma Talwar", title: "Co-Founder", note: "Background details not independently verified." },
      { name: "Sandeep Agarwal", title: "CEO (since 2023)", note: "Background details not independently verified." },
    ],
    website: "xlscout.ai",
    linkedin: "https://www.linkedin.com/company/xlscout-ai",
  }),
  stubCompetitor({
    id: "nlpatent",
    name: "NLPatent (rebranded to Clerq)",
    rank: 12,
    tier: "Tier 2 — Strong Overlap",
    initials: "CQ",
    tagline: "Rebranded as Clerq — agentic AI platform for end-to-end patent work.",
    description:
      "NLPatent rebranded to Clerq on 2026-08-18, launching an agentic AI platform spanning triage assessments through full patentability reports (moving beyond its original LLM-based semantic prior-art search positioning), alongside new partnerships with RPX Corporation and Park IP and a newly hired Director of IP Strategy. See General Highlights.",
        employeeCount: "~25 (est.)",
    founded: "2021",
    hq: "Toronto, Canada",
    founders: [
      { name: "Stephanie Curcio", title: "Co-Founder & CEO", note: "Background as a patent lawyer." },
      { name: "James Stonehill", title: "Co-Founder", note: "Background details not independently verified." },
    ],
    website: "nlpatent.com",
    linkedin: "https://www.linkedin.com/company/nlpatent",
    weekActivity: [
      {
        date: "2026-08-18",
        tag: "Product",
        title: "Rebranded to Clerq, launched agentic patent-work platform",
        body: "New agentic platform covers triage assessments through full patentability reports; announced partnerships with RPX Corporation and Park IP.",
        url: "https://ipwatchdog.com/press/nlpatent-rebrands-to-clerq-unveils-the-next-generation-of-ip-intelligence-built-to-execute-patent-work-end-to-end/",
      },
      {
        date: "2026-08-18",
        tag: "Hiring",
        title: "Hired a Director of IP Strategy",
        body: "New senior IP-strategy hire announced alongside the Clerq rebrand and platform launch.",
        url: "https://www.law360.com/pulse/articles/2512374/nlpatent-rebrands-to-clerq-hires-director-of-ip-strategy",
      },
    ],
  }),
  stubCompetitor({
    id: "patentpal",
    name: "PatentPal",
    rank: 13,
    tier: "Tier 2 — Strong Overlap",
    initials: "PP",
    tagline: "Generative AI patent drafting, including figures and specifications.",
    description: "PatentPal automates generation of patent drafting elements including figures and specifications using generative AI.",
        employeeCount: "2-5 (small team, per Latka)",
    founded: "2018",
    hq: "Foster City, CA",
    founders: [
      { name: "Jack Xu", title: "Founder & CEO", note: "JD, Harvard Law School; prior experience as a patent attorney; background in computer science." },
    ],
    website: "patentpal.com",
    linkedin: "https://www.linkedin.com/company/patentpal",
  }),
  stubCompetitor({
    id: "amplified-ai",
    name: "Amplified AI",
    rank: 14,
    tier: "Tier 2 — Strong Overlap",
    initials: "AA",
    tagline: "AI-powered prior-art and patent search.",
    description: "Amplified AI provides AI-driven prior-art and patent search tooling for patent professionals.",
        employeeCount: "Not verified — no employee count found via LinkedIn/Crunchbase",
    founded: "2017 (concept); platform publicly launched 2020",
    hq: "San Francisco, CA",
    founders: [
      { name: "Sam Davis", title: "CEO", note: "Background details not independently verified." },
      { name: "Chris Grainger", title: "CTO", note: "The patent-search concept grew out of his PhD econometrics research." },
      { name: "Yasu Oikawa", title: "COO", note: "Background details not independently verified." },
    ],
    website: "amplified.ai",
    linkedin: "https://www.linkedin.com/company/amplified-ai",
  }),
  stubCompetitor({
    id: "iprova",
    name: "Iprova",
    rank: 15,
    tier: "Tier 2 — Strong Overlap",
    initials: "IP",
    tagline: "AI-driven invention generation for R&D and IP teams.",
    description: "Iprova uses AI to help R&D and IP teams generate and identify patentable inventions earlier in the innovation cycle — adjacent to Patlytics' search/analytics focus.",
        employeeCount: "~29-31 (LinkedIn/PitchBook/Tracxn)",
    founded: "2010",
    hq: "Lausanne, Switzerland",
    founders: [
      { name: "Julian Nolan", title: "Founder & CEO", note: "B.Eng Electronic Engineering (Univ. of Essex); MSc Artificial Neural Networks; previously at National Instruments, LSI, EMI Music Central Research Labs, and VP Licensing at Honeywell." },
    ],
    website: "iprova.com",
    linkedin: "https://www.linkedin.com/company/iprova",
  }),
  stubCompetitor({
    id: "minesoft",
    name: "Minesoft",
    rank: 16,
    tier: "Tier 2 — Strong Overlap",
    initials: "MS",
    tagline: "Patent search and analytics (PatBase).",
    description: "Minesoft operates PatBase, a long-standing patent search and analytics platform used broadly across the IP professional community.",
        employeeCount: "~88 (Tracxn); LinkedIn lists 51-200",
    founded: "1996",
    hq: "Richmond / London, UK",
    founders: [
      { name: "Ann Chapman-Daniel", title: "Co-Founder & CEO", note: "Background in online publishing and patent information." },
      { name: "Ophir Daniel", title: "Co-Founder", note: "Background as a web developer." },
    ],
    website: "minesoft.com",
    linkedin: "https://www.linkedin.com/company/minesoft-ltd",
  }),
  stubCompetitor({
    id: "questel",
    name: "Questel",
    rank: 17,
    tier: "Tier 2 — Strong Overlap",
    initials: "QU",
    tagline: "Global IP management and Orbit Intelligence analytics.",
    description: "Questel is a global IP management provider whose Orbit Intelligence product competes on patent analytics and search, similar in scope to Clarivate's IP offering. Confirmed a data breach in August 2026 — see this week's activity.",
        employeeCount: "~1,500-1,551 across sources",
    founded: "1978 (as a France Télécom/Orange subsidiary; IP-focused from 2001)",
    hq: "Paris, France",
    founders: [
      { name: "N/A — originated as a telecom subsidiary", title: "Business origin", note: "Current CEO Charles Besson (since 2002) is not documented as the company's founder." },
    ],
    website: "questel.com",
    linkedin: "https://www.linkedin.com/company/questel",
    weekActivity: [
      {
        date: "2026-08-13",
        tag: "Market",
        title: "Confirmed data breach after vishing attack",
        body: "Attackers accessed part of Questel's Microsoft 365 environment via a voice-phishing attack on a Sales SharePoint site; ShinyHunters claims ~21M records / 147GB exfiltrated. Questel notified France's CNIL and filed criminal complaints. See General Highlights.",
        url: "https://www.galaxywarden.com/blog/breach/questel-sas-shinyhunters-2026-08",
      },
    ],
  }),
  stubCompetitor({
    id: "juristat",
    name: "Juristat",
    rank: 18,
    tier: "Tier 2 — Strong Overlap",
    initials: "JU",
    tagline: "AI patent prosecution analytics and examiner statistics.",
    description: "Juristat provides AI-driven analytics on patent prosecution, including examiner-level statistics, to help attorneys plan prosecution strategy.",
        employeeCount: "28-41 depending on source",
    founded: "2012",
    hq: "Webster Groves / St. Louis, MO",
    founders: [
      { name: "Robert Ward", title: "Co-Founder", note: "Previously a Computer Engineer at Beck Automation (industrial controls, real-time C/C++)." },
      { name: "Drew Winship", title: "Co-Founder", note: "Background details not independently verified." },
    ],
    website: "juristat.com",
    linkedin: "https://www.linkedin.com/company/juristat",
  }),
  stubCompetitor({
    id: "patent-bots",
    name: "Patent Bots",
    rank: 19,
    tier: "Tier 2 — Strong Overlap",
    initials: "PB",
    tagline: "AI and rules-based patent drafting, proofreading, and examiner stats.",
    description: "Patent Bots combines rules-based and AI tooling for patent drafting, proofreading, and examiner statistics.",
        employeeCount: "~7-9",
    founded: "2018",
    hq: "Somerville, MA",
    founders: [
      { name: "Jeff O'Neill", title: "Founder & CEO", note: "Patent attorney; former in-house patent counsel at Amazon, associate at Wolf Greenfield, and clerk for the First Circuit Court of Appeals." },
    ],
    website: "patentbots.com",
    linkedin: "https://www.linkedin.com/company/patent-bots",
    weekActivity: [
      {
        date: "2026-08-10",
        tag: "Product",
        title: "Shipped 'Gen AI Chat' for office-action response drafting",
        body: "New chat feature automatically pulls the relevant office action, spec, and prior art to guide OA response drafting. (Exact publish date approximate — company blog is dated August 2026.)",
        url: "https://blog.patentbots.com/2026/08/new-in-patent-bots-gen-ai-chat-now.html",
      },
    ],
  }),
  stubCompetitor({
    id: "alt-legal",
    name: "Alt Legal",
    rank: 20,
    tier: "Tier 2 — Strong Overlap",
    initials: "AL",
    tagline: "AI-assisted IP and trademark docketing.",
    description: "Alt Legal provides AI-assisted docketing software for IP and trademark portfolios, overlapping with Patlytics primarily on the operations/docketing side. Acquired UK-based WebTMS in April 2026 to add global IP portfolio management.",
        employeeCount: "~54 (Tracxn, 2026)",
    founded: "2013",
    hq: "New York, NY",
    founders: [
      { name: "Nehal Madhani", title: "Founder & CEO", note: "JD, University of Pennsylvania Law School; Wharton certificate; BA Northwestern; former attorney at Kirkland & Ellis; CodeX fellow at Stanford Law School." },
      { name: "Gabe Kneisley", title: "Co-Founder & Head of Product", note: "Background as a product/interaction designer." },
    ],
    website: "altlegal.com",
    linkedin: "https://www.linkedin.com/company/alt-legal-ip-management-software",
    weekActivity: [
      {
        date: "2026-08-20",
        tag: "Marketing",
        title: "Published brand-monitoring content on ICANN's 2026 New gTLD Program",
        body: "Blog content on how ICANN's 2026 New gTLD Program expansion affects brand monitoring, alongside a hosted webinar on trademark management software selection featuring Warner Music Group's Sofya Nadgorny.",
        url: "https://www.altlegal.com/blog/2026gtlds/",
      },
    ],
  }),
  stubCompetitor({
    id: "pqai",
    name: "PQAI",
    rank: 21,
    tier: "Tier 2 — Strong Overlap",
    initials: "PQ",
    tagline: "Free, open-source AI prior-art search (nonprofit, AT&T-backed).",
    description: "PQAI is a free, open-source AI-powered prior-art search tool backed by AT&T, notable as a nonprofit/open alternative in the same search category Patlytics competes in.",
        employeeCount: "Very small team (2-10) — confirmed nonprofit/open-source initiative, not a traditional company",
    founded: "~2019",
    hq: "United States (AT&T-initiated; no single traditional HQ)",
    founders: [
      { name: "Sam Zellner", title: "Project Lead", note: "Former AT&T IP executive with 200+ patents; PQAI is an MIT-licensed open-source project initiated by AT&T's IP organization, not a founder-led startup." },
    ],
    website: "projectpq.ai",
    linkedin: "https://www.linkedin.com/company/pqai",
  }),
  stubCompetitor({
    id: "harvey",
    name: "Harvey",
    rank: 25,
    tier: "Tier 3 — Adjacent",
    initials: "HV",
    tagline: "Domain-specific generative AI for law firms and professional services.",
    description: "Harvey provides generalist domain-specific AI for AmLaw firms and professional services. Internally, Patlytics reps treat Harvey as a 'generalist AI' wedge competitor — the pitch being that Patlytics offers real IP-specific depth where Harvey is broad but shallow on patents.",
        employeeCount: "~1,561 (mid-2026)",
    founded: "2022",
    hq: "San Francisco, CA",
    founders: [
      { name: "Winston Weinberg", title: "Co-Founder & CEO", note: "JD, USC Gould School of Law; BA Kenyon College; former securities/antitrust litigation associate at O'Melveny & Myers." },
      { name: "Gabriel Pereyra", title: "Co-Founder & President", note: "CS degree, USC; Google Brain resident, then research scientist at DeepMind, then ML engineer at Meta." },
    ],
    website: "harvey.ai",
    linkedin: "https://www.linkedin.com/company/harvey-ai",
    weekActivity: [
      {
        date: "2026-08-18",
        tag: "Product",
        title: "Launched 'Harvey II' with persistent cross-app Memory",
        body: "New platform centered on a Memory feature that learns individual lawyer/client preferences across Harvey, Word, Outlook, and its agents. See General Highlights.",
        url: "https://www.artificiallawyer.com/2026/08/18/next-gen-harvey-ii-launches-with-memory-at-its-core/",
      },
      {
        date: "2026-08-07",
        tag: "Funding",
        title: "Reportedly in talks to raise ~$500M at a $15.5B valuation",
        body: "Reported round led by Lightspeed, up from an $11B valuation in March 2026; Goldman Sachs Alternatives and J.P. Morgan Growth Equity Partners reportedly invested in late July. Not yet a confirmed closed round.",
        url: "https://siliconangle.com/2026/08/07/legal-ai-startup-harvey-reportedly-raising-500m-15-5b-valuation/",
      },
    ],
  }),
  stubCompetitor({
    id: "legora",
    name: "Legora",
    rank: 26,
    tier: "Tier 3 — Adjacent",
    initials: "LG",
    tagline: "Collaborative generative AI for lawyers (review, drafting, research). Formerly branded 'Leya'.",
    description: "Legora offers collaborative generative AI for legal review, drafting, and research. Like Harvey, it's used internally as a generalist-AI comparison point in sales conversations rather than a head-to-head IP competitor. Note: this company was formerly branded 'Leya' (rebranded 2025) — see the separate Leya entry in this list, kept for historical continuity.",
        employeeCount: "~614 (Tracxn, mid-2026)",
    founded: "2023 (renamed from Leya to Legora, February 2025)",
    hq: "Stockholm, Sweden",
    founders: [
      { name: "Max Junestrand", title: "Co-Founder & CEO", note: "BSc Economics (Stockholm School of Economics); MSc Computer Science/ML (KTH); prior venture capital experience." },
      { name: "Sigge Labor", title: "Co-Founder & CTO", note: "Building legal-AI tools since 2020." },
      { name: "August Erséus", title: "Co-Founder (former CPO)", note: "Building legal-AI tools since 2020." },
    ],
    website: "legora.com",
    linkedin: "https://www.linkedin.com/company/wearelegora",
    weekActivity: [
      {
        date: "2026-08-17",
        tag: "Product",
        title: "Announced integration with Box",
        body: "Integration agreement with content-management platform Box, in beta this quarter.",
        url: "https://www.globallegalpost.com/news/legora-announces-integration-agreement-with-content-management-intelligence-platform-box-1821553996",
      },
      {
        date: "2026-08-13",
        tag: "Funding",
        title: "Reportedly in talks to raise at a $10B valuation",
        body: "Nearly double its $5.6B Series D valuation from March 2026. Not yet a confirmed closed round. See General Highlights.",
        url: "https://sifted.eu/articles/legora-in-talks-to-raise-at-a-10bn-valuation-according-to-reports",
      },
    ],
  }),
  stubCompetitor({
    id: "spellbook",
    name: "Spellbook",
    rank: 27,
    tier: "Tier 3 — Adjacent",
    initials: "SB",
    tagline: "AI contract review and drafting inside Microsoft Word.",
    description: "Spellbook provides AI-assisted contract review and drafting directly inside Microsoft Word, primarily for transactional/commercial legal work rather than patents.",
        employeeCount: "~46 (2026)",
    founded: "2018 (product launched 2022)",
    hq: "Toronto, Canada",
    founders: [
      { name: "Scott Stevenson", title: "Co-Founder & CEO", note: "Background details not independently verified." },
      { name: "Daniel Di Maria", title: "Co-Founder & CRO", note: "Background details not independently verified." },
      { name: "Matt Mayers", title: "Co-Founder & Chief Experience Officer", note: "Background details not independently verified." },
    ],
    website: "spellbook.legal",
    linkedin: "https://www.linkedin.com/company/spellbookai",
    weekActivity: [
      {
        date: "2026-08-15",
        tag: "Partnership",
        title: "Named exclusive AI drafting/review provider for the Canadian Bar Association",
        body: "Two-year deal covers the CBA's 40,000+ member base. Also secured $40M in debt financing from RBCx for acquisitions and reports being on track for $100M ARR in 2026. (Exact announcement date approximate — not stated precisely in source.)",
        url: "https://betakit.com/on-track-to-hit-100-million-usd-arr-spellbook-partners-with-canadian-bar-association/",
      },
    ],
  }),
  stubCompetitor({
    id: "robin-ai",
    name: "Robin AI",
    rank: 28,
    tier: "Tier 3 — Adjacent",
    initials: "RA",
    tagline: "AI contract copilot for review and negotiation. WOUND DOWN — see note.",
    description: "Robin AI offered an AI copilot for contract review and negotiation. After a planned $50M raise fell through in October 2025, the company laid off roughly a third of staff and sought a buyer; its managed-services arm was acquired by Scissero in December 2025, and Microsoft absorbed its engineering team in January 2026 to bolster Word's legal-AI features. Confirmed no longer operating as an independent company (verified 2026-08-25, see General Highlights).",
    employeeCount: "N/A — wound down as an independent company (see description)",
    founded: "2019 (ceased independent operation 2025-2026)",
    hq: "London, UK (historical)",
    website: "robinai.com",
    linkedin: "https://www.linkedin.com/company/robinai",
    founders: [
      { name: "Richard Robinson", title: "Co-Founder", note: "Formerly a lawyer at Clifford Chance." },
      { name: "Dr. James Clough", title: "Co-Founder", note: "Machine-learning research scientist." },
    ],
  }),
  stubCompetitor({
    id: "leya",
    name: "Leya",
    rank: 29,
    tier: "Tier 3 — Adjacent",
    initials: "LY",
    tagline: "Generative AI for legal workflows (Nordics/Europe). Rebranded as Legora in 2025 — kept here for historical continuity only.",
    description: "Leya provided generative AI tooling across general legal workflows, primarily in the Nordics/European market. The company rebranded to 'Legora' in 2025; all current activity, funding, and product news is tracked under the Legora entry in this list, not here.",
    employeeCount: "N/A — see Legora entry for current headcount",
    founded: "2019 (rebranded to Legora, February 2025)",
    hq: "Stockholm, Sweden",
    website: "leyalaw.com",
    linkedin: "https://www.linkedin.com/company/leyalaw",
    founders: [
      { name: "Max Junestrand", title: "Co-Founder & CEO", note: "BSc Economics (Stockholm School of Economics); MSc Computer Science/ML (KTH); prior venture capital experience." },
      { name: "Sigge Labor", title: "Co-Founder & CTO", note: "Building legal-AI tools since 2020." },
      { name: "August Erséus", title: "Co-Founder (former CPO)", note: "Building legal-AI tools since 2020." },
    ],
  }),
  stubCompetitor({
    id: "cocounsel",
    name: "Casetext (CoCounsel)",
    rank: 30,
    tier: "Tier 3 — Adjacent",
    initials: "CC",
    tagline: "AI legal assistant, now part of Thomson Reuters.",
    description: "Casetext's CoCounsel AI legal assistant was acquired by Thomson Reuters and is now distributed as part of its broader legal AI suite — relevant to watch given Thomson Reuters' expanding legal-AI partnership activity (see General Highlights re: the reported Solve Intelligence partnership).",
        employeeCount: "~100 at acquisition (Aug 2023); now fully absorbed into Thomson Reuters (~26,000+ employees) — a standalone count is no longer meaningful",
    founded: "2013",
    hq: "San Francisco, CA (pre-acquisition); now part of Thomson Reuters",
    founders: [
      { name: "Jake Heller", title: "Co-Founder & CEO", note: "Stanford JD '10. Casetext was acquired by Thomson Reuters for $650M, closed Aug 2023." },
      { name: "Pablo Arredondo", title: "Co-Founder", note: "Stanford JD '05." },
      { name: "Laura Safdie", title: "Co-Founder", note: "Background details not independently verified." },
    ],
    website: "legal.thomsonreuters.com",
    linkedin: "https://www.linkedin.com/company/casetext",
    weekActivity: [
      {
        date: "2026-08-20",
        tag: "Product",
        title: "Launched next-generation agentic CoCounsel Legal",
        body: "General availability of Westlaw Brief Builder, Workspaces, a Word-integrated Drafting Agent, and Tabular Analysis, alongside Thomson Reuters' own proprietary LLM ('Thomson') and an expanded MCP integration with Anthropic's Claude.",
        url: "https://www.thomsonreuters.com/en/press-releases/2026/august/thomson-reuters-launches-next-generation-of-cocounsel-legal-the-ai-ecosystem-built-for-legal-professionals",
      },
    ],
  }),
  stubCompetitor({
    id: "ironclad",
    name: "Ironclad",
    rank: 31,
    tier: "Tier 3 — Adjacent",
    initials: "IC",
    tagline: "AI-powered contract lifecycle management.",
    description: "Ironclad provides AI-powered contract lifecycle management software, adjacent to Patlytics mainly as a broader legal-tech budget line item.",
        employeeCount: "~800 (estimates range 763-866 across data providers)",
    founded: "2014",
    hq: "San Francisco, CA",
    founders: [
      { name: "Jason Boehmig", title: "Co-Founder (former CEO, now Executive Chairman)", note: "Previously a corporate attorney at Fenwick & West; Notre Dame JD; joined OpenAI in 2026 to build legal products." },
      { name: "Cai GoGwilt", title: "Co-Founder", note: "Former software engineer at Palantir Technologies." },
    ],
    website: "ironcladapp.com",
    linkedin: "https://www.linkedin.com/company/ironclad-inc-",
    weekActivity: [
      {
        date: "2026-08-05",
        tag: "Product",
        title: "Launched AI agents for procurement teams",
        body: "New agents handle obligation tracking, precedent-based redlining, and enhanced SAP integration for procurement teams. See General Highlights.",
        url: "https://www.prnewswire.com/news-releases/ironclad-launches-ai-agents-to-help-procurement-teams-save-money-move-faster-and-manage-risk-302843168.html",
      },
    ],
  }),
  stubCompetitor({
    id: "linksquares",
    name: "LinkSquares",
    rank: 32,
    tier: "Tier 3 — Adjacent",
    initials: "LS",
    tagline: "AI-powered contract lifecycle management (\"LinkAI\").",
    description: "LinkSquares offers AI-powered contract lifecycle management under its LinkAI branding, competing in the broader legal-AI category.",
        employeeCount: "400+ (self-reported)",
    founded: "2015",
    hq: "Boston, MA",
    founders: [
      { name: "Vishal Sunak", title: "Co-Founder (board member)", note: "Background details not independently verified." },
      { name: "Chris Combs", title: "Co-Founder", note: "Background details not independently verified." },
    ],
    website: "linksquares.com",
    linkedin: "https://www.linkedin.com/company/linksquares",
    weekActivity: [
      {
        date: "2026-08-19",
        tag: "Hiring",
        title: "Named Lyle McCutcheon-Schour SVP of Revenue",
        body: "New SVP of Revenue hire announced to drive agentic CLM growth; also appeared on the 2026 Inc. 5000 list on Aug 11, 2026.",
        url: "https://www.streetinsider.com/PRNewswire/LinkSquares+Names+Lyle+McCutcheon-Schour+SVP+of+Revenue+to+Drive+Agentic+CLM+Growth/26948572.html",
      },
    ],
  }),
  stubCompetitor({
    id: "draftwise",
    name: "DraftWise",
    rank: 33,
    tier: "Tier 3 — Adjacent",
    initials: "DW",
    tagline: "AI contract drafting and negotiation using firm knowledge.",
    description: "DraftWise uses a law firm's own historical documents to power AI-assisted contract drafting and negotiation — a broader legal-AI adjacent player.",
    employeeCount: "71 (as of May 2026)",
    founded: "2020",
    hq: "New York, NY",
    founders: [
      { name: "James Ding", title: "Co-Founder & CEO", note: "Former Palantir engineering leader." },
      { name: "Emre Ozen", title: "Co-Founder", note: "Former Palantir engineering leader." },
      { name: "Ozan Yalti", title: "Co-Founder", note: "Stanford Law graduate; practiced at Clifford Chance." },
    ],
    website: "draftwise.com",
    linkedin: "https://www.linkedin.com/company/draftwise-ai",
    weekActivity: [
      {
        date: "2026-08-24",
        tag: "Product",
        title: "Launched \"Legal Ontology\" framework",
        body: "A framework meant to capture the judgment layer behind law-firm documents — modeling relationships/decisions rather than just document text.",
        url: "https://www.artificiallawyer.com/2026/08/24/draftwise-launches-legal-ontology-to-capture-the-judgment-layer/",
      },
    ],
  }),
  stubCompetitor({
    id: "genie-ai",
    name: "Genie AI",
    rank: 34,
    tier: "Tier 3 — Adjacent",
    initials: "GA",
    tagline: "AI legal contract drafting and templates.",
    description: "Genie AI provides AI-assisted legal contract drafting and template generation for a broad legal audience.",
        employeeCount: "11-50",
    founded: "2017",
    hq: "Cambridge / London, England",
    founders: [
      { name: "Rafie Faruq", title: "Co-Founder & CEO", note: "Former derivatives trader." },
      { name: "Nitish Mutha", title: "Co-Founder & CTO", note: "Met Faruq as UCL machine-learning master's classmates." },
    ],
    website: "genieai.co",
    linkedin: "https://www.linkedin.com/company/genie-ai",
  }),
  stubCompetitor({
    id: "eve-legal",
    name: "Eve",
    rank: 35,
    tier: "Tier 3 — Adjacent",
    initials: "EV",
    tagline: "AI legal assistant for plaintiff firms.",
    description: "Eve provides an AI legal assistant built specifically for plaintiff-side law firms, a niche broader-legal-AI adjacent player.",
        employeeCount: "~314 (as of June 2026)",
    founded: "2023",
    hq: "San Francisco, CA",
    founders: [
      { name: "Jay Madheswaran", title: "Founder & CEO", note: "Background details not independently verified." },
      { name: "David Zeng", title: "Co-Founder", note: "Background details not independently verified." },
      { name: "Matt Noe", title: "Co-Founder", note: "Background details not independently verified." },
    ],
    website: "eve.legal",
    linkedin: "https://www.linkedin.com/company/eve-legal",
  }),
  stubCompetitor({
    id: "park-ip",
    name: "Park IP (Legal Studio)",
    rank: 36,
    tier: "Tier 3 — Adjacent",
    initials: "PI",
    tagline: "AI-powered global patent filing and translation workflow platform.",
    description:
      "Park IP (a Welo Global/Welocalize brand) is an established global patent-translation and IP-filing services provider serving Am Law 100 and Fortune 500 IP departments. It launched 'Legal Studio,' an AI-powered platform combining automation, AI quality control, and analytics across patent filing workflows in 180+ jurisdictions — an incumbent moving AI tooling into patent-adjacent workflow territory with existing enterprise distribution. Newly identified in this sweep; added 2026-08-25.",
        employeeCount: "Not verified — no reliable current headcount found",
    founded: "1997 (as Park IP Translations; acquired by Welocalize in 2012; now a client-facing brand of Welo Global)",
    hq: "New York, NY",
    founders: [
      { name: "N/A — legacy service line, not a founder-led startup", title: "Business origin", note: "Now operates under Welo Global; current leaders are Erin Wynn (GM, Park IP), Hugh McCallion (Sr. Director, Legal Studio), and Paul Carr (CEO, Welo Global)." },
    ],
    website: "parkip.com",
    linkedin: null,
  }),
  stubCompetitor({
    id: "patseer",
    name: "PatSeer (Gridlogics)",
    rank: 4.5,
    tier: "Tier 1 — Direct Competitor",
    initials: "PT",
    tagline: "AI-driven patent search, analytics, and landscaping platform.",
    description: "PatSeer, built by Gridlogics, is a long-established AI-driven patent search and analytics platform covering 165M+ patents across 108+ countries, used by 8,000+ IP professionals. Comparable in scale and positioning to PatSnap/Minesoft — a notable direct competitor. Identified via gap-check research; added 2026-08-25.",
        employeeCount: "~114-116 (LinkedIn/Tracxn band: 51-200)",
    founded: "Gridlogics Technologies founded 2004; PatSeer product launched ~2012-2013 (sources conflict on exact year)",
    hq: "Pune, Maharashtra, India",
    founders: [
      { name: "Manish Sinha", title: "Founder & CTO", note: "Previously at Hughes Software Systems." },
    ],
    website: "patseer.com",
    linkedin: "https://www.linkedin.com/company/patseer-technologies",
  }),
  stubCompetitor({
    id: "patently",
    name: "Patently",
    rank: 9.5,
    tier: "Tier 1 — Direct Competitor",
    initials: "PL",
    tagline: "Full patent-lifecycle AI platform: drafting, prosecution, and semantic search.",
    description: "Patently offers an AI drafting assistant, AI-enhanced prosecution tooling, and vector/semantic AI patent search — overlapping closely with Patlytics' own search + draft + prosecute positioning. Small LinkedIn footprint (~127 followers) as of this writing. Identified via gap-check research; added 2026-08-25.",
        employeeCount: "11-50",
    founded: "2018",
    hq: "London, England, UK",
    founders: [
      { name: "Jerome Spaargaren", title: "Co-Founder", note: "Patent attorney/litigator." },
      { name: "Heather McCann", title: "Co-Founder", note: "Patent attorney/litigator." },
    ],
    website: "patently.com",
    linkedin: "https://www.linkedin.com/company/patently",
  }),
  stubCompetitor({
    id: "ip-author",
    name: "IP Author (by Dolcera)",
    rank: 9.6,
    tier: "Tier 1 — Direct Competitor",
    initials: "IA",
    tagline: "AI-powered patent drafting tool for law firms and corporate IP teams.",
    description: "IP Author, built by Dolcera, generates claims, background, and description sections for patent applications, with a zero-data-retention OpenAI integration aimed at law firms and corporate patent teams. Direct overlap with Patlytics/Solve/DeepIP-style AI drafting. Identified via gap-check research; added 2026-08-25.",
        employeeCount: "~149-154 (sources vary)",
    founded: "Dolcera founded 2004; IP Author is a later product line",
    hq: "San Mateo, CA (also Hyderabad, India office)",
    founders: [
      { name: "Lakshmikant Goenka", title: "Founder & Managing Director", note: "B.S. in Chemistry; MBA from MDI Gurgaon; previously in sales/product roles at Pidilite Industries and United Chemie. One source separately lists a 'Samir Raiyani' as CEO — not independently corroborated." },
    ],
    website: "ipauthor.com",
    linkedin: "https://www.linkedin.com/company/dolcera",
  }),
  stubCompetitor({
    id: "powerpatent",
    name: "PowerPatent",
    rank: 9.7,
    tier: "Tier 1 — Direct Competitor",
    initials: "PP",
    tagline: "AI patent drafting software built by patent attorneys, with human attorney review.",
    description: "PowerPatent focuses on AI-assisted provisional patent applications for startups and independent inventors, layering human-attorney review on top of AI drafting. Frequently listed alongside Solve Intelligence/DeepIP in comparison articles. Identified via gap-check research; added 2026-08-25.",
        employeeCount: "2-10 per LinkedIn; other aggregators show 7-13 — not fully reconciled",
    founded: "Not verified — conflicting sources (LinkedIn shows 2020, other aggregators show 2010); company site doesn't state a founding year",
    hq: "Santa Clara, CA",
    founders: [
      { name: "Bao Tran", title: "Founder & CEO", note: "JD, University of Houston Law Center; MBA, Columbia University; BSEE, Rice University; also Managing Partner at patent law firm PatentPC, licensed patent attorney in CA/NV/TX and before the USPTO." },
    ],
    website: "powerpatent.com",
    linkedin: "https://www.linkedin.com/company/powerpatent-inc-",
  }),
  stubCompetitor({
    id: "cypris",
    name: "Cypris",
    rank: 15.5,
    tier: "Tier 2 — Strong Overlap",
    initials: "CY",
    tagline: "AI-powered R&D and innovation-intelligence platform spanning patents, papers, and market data.",
    description: "Cypris combines 500M+ patents, research papers, and market data with multimodal AI (integrating OpenAI/Anthropic/Google models) for R&D and innovation intelligence — broader than pure patent prosecution, but frequently named alongside PatSnap/IPRally in 2026 'AI patent tools' roundups. Pivoted from an earlier patent-marketplace model in 2019. Identified via gap-check research; added 2026-08-25.",
        employeeCount: "~11-50 (LinkedIn); Tracxn shows ~40 (May 2026)",
    founded: "2020",
    hq: "New York, NY",
    founders: [
      { name: "Steve Hafif", title: "Founder & CEO", note: "Studied data science at Drexel University; co-op placement with Exelon's R&D innovation team building internal patent-data search tools." },
      { name: "Amir Achourie", title: "Co-Founder", note: "Background details not independently verified." },
    ],
    website: "cypris.ai",
    linkedin: "https://www.linkedin.com/company/cyprisai",
  })
);

/* ---------------- New Market Entrants ---------------- */
// Every entrant below is a REAL, currently active company, verified via
// press coverage / YC / Crunchbase / the company's own site at the time
// this file was written. Specific hiring-volume numbers are not yet
// scraped from live careers pages, so that field is intentionally left
// as "not yet verified" rather than guessed.
const NEW_ENTRANTS = [
  {
    id: "stilta",
    name: "Stilta",
    threat: "high",
    backing: "a16z-led $10.5M seed (Y Combinator W26)",
    stage: "Seed",
    tagline: "Agentic AI for patent litigation, invalidity, and infringement analysis.",
    website: "https://stilta.com",
    linkedin: null,
    description:
      "Stockholm-based Stilta builds agentic AI for IP work, starting with patent litigation — every output is source-backed and auditable. Already used by multiple AmLaw 100 firms and Fortune 500 in-house IP teams within months of its December 2025 founding.",
    foundingTeam: [
      { name: "Oskar Block", background: "CEO. Previously McKinsey, Goldman Sachs, and Swedish unicorns." },
      { name: "3 additional co-founders", background: "Also former McKinsey/QuantumBlack engineers (names pending verification)." },
    ],
    hiring: {
      openRoles: null,
      focus: "Not yet verified — careers page not yet scraped",
      hiringProfile: "Not yet verified.",
    },
    date: d(-6),
    source: "TechCrunch, LawNext",
    sourceUrl: "https://techcrunch.com/2026/05/19/legal-tech-announced-stilta-announces-10m-seed-backed-by-yc-and-a16z-months-after-launch/",
  },
  {
    id: "and-ai",
    name: "&AI",
    threat: "high",
    backing: "$6.5M seed led by First Round (Y Combinator)",
    stage: "Seed",
    tagline: "\"Andy\" — an AI agent for patent prior art search, claim charts, and office actions.",
    website: "https://www.tryandai.com",
    linkedin: "https://www.linkedin.com/company/and-ai",
    description:
      "San Francisco-based &AI built Andy, an AI agent for patent attorneys handling prior art search, claim chart drafting, and office-action responses. Early large-firm customers report 70-90% time savings on claim-chart work.",
    foundingTeam: [
      { name: "Caleb Harris", background: "Co-Founder. MIT. Previously a technical advisor to law firms on patent issues." },
      { name: "Herbert Turner", background: "Co-Founder. MIT." },
    ],
    hiring: {
      openRoles: null,
      focus: "Not yet verified — careers page not yet scraped",
      hiringProfile: "Not yet verified.",
    },
    date: d(-9),
    source: "Artificial Lawyer, IPWatchdog",
    sourceUrl: "https://www.artificiallawyer.com/2025/02/06/yc-backed-ai-raises-6-5m-launches-ai-agent-for-patent-work/",
  },
  {
    id: "fearn",
    name: "Fearn",
    threat: "high",
    backing: "$5.5M seed led by Kindred Ventures, w/ a16z speedrun",
    stage: "Seed",
    tagline: "AI-native patent drafting platform — draft a full patent application in ~20 minutes.",
    website: "https://fearn.ai",
    linkedin: null,
    description:
      "San Francisco-based Fearn pairs purpose-built, hallucination-resistant drafting models with automated labeled-figure generation, aiming to cut patent drafting time by ~96% and bring Big-Law-quality drafting to solo inventors and startups first.",
    foundingTeam: [
      { name: "Han Kim", background: "Co-Founder & CEO. Caltech (ML research). Previously scientific analyst at Morrison Foerster." },
      { name: "Angela Gao", background: "Co-Founder & CTO. PhD, Caltech. Previously developed AI models at Google Research." },
    ],
    hiring: {
      openRoles: null,
      focus: "Not yet verified — careers page not yet scraped",
      hiringProfile: "Not yet verified.",
    },
    date: d(-15),
    source: "PR Newswire, Law.com",
    sourceUrl: "https://www.prnewswire.com/news-releases/fearn-raises-5-5-million-seed-to-end-the-two-tier-patent-system-302796012.html",
  },
  {
    id: "patent-watch",
    name: "Patent Watch",
    threat: "medium",
    backing: "$2.8M seed (Y Combinator F25, FundersClub, Transpose, Blast)",
    stage: "Seed",
    tagline: "AI for patent infringement detection, claim charts, and freedom-to-operate assessments.",
    website: "https://www.patentwatch.ai",
    linkedin: "https://www.linkedin.com/company/patentwatch-ai",
    description:
      "Toronto-based Patent Watch automates infringement detection — interpreting patents, identifying competing products, and generating claim charts to support licensing, litigation, and M&A diligence workflows in roughly 20 minutes per analysis.",
    foundingTeam: [
      { name: "Alexander Stroe", background: "Co-Founder. Deep domain expertise in patent enforcement." },
      { name: "Andreas Stroe", background: "Co-Founder. Former Philips research engineer, named inventor on multiple patents." },
    ],
    hiring: {
      openRoles: null,
      focus: "Not yet verified — careers page not yet scraped",
      hiringProfile: "Not yet verified.",
    },
    date: d(-18),
    source: "Crunchbase, LegalTech.ca",
    sourceUrl: "https://legaltech.ca/2026/05/28/yc-toronto-startup-patents-revenue-ai-toolkit/",
  },
  {
    id: "newcode-ai",
    name: "Newcode",
    threat: "low",
    backing: "$13.5M Series A led by OnDean Forward (Relativity founder Andrew Sieja's fund), w/ Rel Labs & The LegalTech Fund",
    stage: "Series A",
    tagline: "Configurable AI harness for law firms — document analysis, review, translation, enterprise search.",
    website: "https://newcode.ai",
    linkedin: null,
    description:
      "Oslo/Dublin-based Newcode builds a configurable AI harness that law firms deploy in-house for document analysis, review, translation, and enterprise search. Not patent-specific — a general legal-AI adjacent entrant included for completeness. Brings total 2026 funding to roughly $20M after a $6.5M round in March.",
    foundingTeam: [
      { name: "Maged Helmy", background: "Founder. PhD in AI, University of Oslo; Associate Professor. Background pending fuller independent verification beyond trade-press bios." },
    ],
    hiring: {
      openRoles: null,
      focus: "Not yet verified — careers page not yet scraped",
      hiringProfile: "Not yet verified.",
    },
    date: "2026-08-24",
    source: "Law.com Legaltech News, Artificial Lawyer",
    sourceUrl: "https://www.law.com/legaltechnews/2026/08/24/legal-ai-startup-newcode-announces-135m-series-a-round-with-investment-from-relativity/",
  },
  {
    id: "aavalynx",
    name: "Aavalynx",
    threat: "low",
    backing: "£1.5M (~$1.9M) pre-seed led by Omega Ventures, w/ Two Ravens",
    stage: "Pre-seed",
    tagline: "AI \"case intelligence\" platform (\"Sisu\") for litigation and dispute portfolio risk analysis.",
    website: "https://aavalynx.ai",
    linkedin: null,
    description:
      "London-based Aavalynx (product name 'Sisu') applies AI to help corporate legal teams analyze litigation and dispute portfolio risk. Adjacent to litigation-analytics players rather than core patent search/drafting — included for completeness.",
    foundingTeam: [
      { name: "Hanna Roos", background: "Co-Founder & CEO. Former disputes lawyer at Freshfields, Latham & Watkins, and Quinn Emanuel; also founded boutique firm Aavagard." },
      { name: "Lauri Hyry", background: "Co-Founder. Mathematics/entrepreneurship background." },
    ],
    hiring: {
      openRoles: null,
      focus: "Not yet verified — careers page not yet scraped",
      hiringProfile: "Not yet verified.",
    },
    date: "2026-08-05",
    source: "Artificial Lawyer, Tech.eu, EU-Startups",
    sourceUrl: "https://www.artificiallawyer.com/2026/08/05/aavalynx-raises-1-5m-pre-seed-for-litigation-insights/",
  },
  {
    id: "lightbringer",
    name: "Lightbringer",
    threat: "medium",
    backing: "$10M Series A (~€8.6M) co-led by 6 Degrees Capital and Newion",
    stage: "Series A",
    tagline: "AI-native, full-service patent provider — AI paired with in-house patent attorneys.",
    website: "https://lightbringer.com",
    linkedin: null,
    description:
      "Malmö, Sweden-based Lightbringer pairs AI with in-house patent attorneys to offer a full-service patent process (idea capture through drafting, prosecution/office actions, and portfolio management), aimed at startups and scale-ups. Raised a $10M Series A in mid-June 2026 (co-led by 6 Degrees Capital and Newion, with existing investors Luminar Ventures and Alliance VC); press reports cite 300% YoY revenue growth in Q2 2026 and plans to expand into the US market.",
    foundingTeam: [
      { name: "Dominic Davies", background: "Co-Founder & CEO. Former patent attorney." },
      { name: "Ola Wassvik", background: "Co-Founder." },
      { name: "Markus Andreasson", background: "Co-Founder." },
    ],
    hiring: {
      openRoles: null,
      focus: "Not yet verified — careers page not yet scraped",
      hiringProfile: "Not yet verified.",
    },
    date: "2026-06-16",
    source: "ArcticStartup, EU-Startups, Global Legal Post, Tech Funding News",
    sourceUrl: "https://www.eu-startups.com/2026/06/swedish-ai-patent-platform-lightbringer-raises-e8-6-million-to-take-on-big-law-and-replace-existing-patent-firms",
  },
];

/* ---------------- Webinars ---------------- */
// Verified via each host's own events/webinar pages and the IPWatchdog
// events-listing partner program (2026-08-25 research pass). Every entry
// below has a real, working source URL — no placeholder/sample listings.
const WEBINARS = [
  {
    id: "wb-1",
    title: "AI-Powered Patent Landscaping",
    host: "LexisNexis Cipher",
    date: "2026-08-18",
    time: "See registration page",
    format: "Live webinar",
    relevance: "high",
    description:
      "Session on AI-driven landscaping methodology for patent portfolios, listed via IPWatchdog's events partner program.",
    tags: ["Landscaping", "Competitor-hosted"],
    url: "https://ipwatchdog.com/event/webinar-lexisnexis-2026-08-18-ai-powered-patent-landscaping/",
  },
  {
    id: "wb-2",
    title: "AI for Lean IP Teams — Doing More with Less While Empowering the Next Generation",
    host: "Anaqua",
    date: "2026-08-25",
    time: "12:00 PM ET",
    format: "Live webinar",
    relevance: "high",
    description:
      "Live session (today) on helping lean IP teams adopt AI while empowering junior staff, without adding headcount.",
    tags: ["Competitor-hosted", "AI Adoption"],
    url: "https://ipwatchdog.com/event/webinar-anaqua-2026-08-25-ai-for-lean-ip-teams/",
  },
  {
    id: "wb-3",
    title: "Patent Forecasting and Budgeting",
    host: "Juristat",
    date: "2026-08-11",
    time: "See registration page",
    format: "Live webinar",
    relevance: "medium",
    description: "Session on using AI-driven prosecution analytics to forecast patent budgets and timelines.",
    tags: ["Competitor-hosted", "Analytics"],
    url: "https://ipwatchdog.com/event/webinar-juristat-2026-08-11-patent-forecasting-and-budgeting/",
  },
  {
    id: "wb-4",
    title: "AI Capabilities and the Future in Life Sciences Patent Practice",
    host: "Solve Intelligence",
    date: "2026-08-27",
    time: "See registration page",
    format: "Live webinar",
    relevance: "high",
    description:
      "Covers new sequence-handling/data-import features for life sciences patent drafting and claim charts.",
    tags: ["Competitor-hosted", "Life Sciences", "AI Drafting"],
    url: "https://ipwatchdog.com/solve-intelligence-august-27-2026/",
  },
  {
    id: "wb-5",
    title: "Building an IPO-Ready Patent Strategy",
    host: "Tradespace",
    date: "2026-09-01",
    time: "See registration page",
    format: "Live webinar",
    relevance: "medium",
    description: "Session on structuring a defensible patent strategy ahead of an IPO.",
    tags: ["Patent Strategy"],
    url: "https://ipwatchdog.com/event/webinar-tradespace-2026-09-01-building-an-ipo-ready-patent-strategy/",
  },
  {
    id: "wb-6",
    title: "Before the Draft — Deciding What Is Worth Patenting in the AI Era",
    host: "IP.com",
    date: "2026-09-03",
    time: "12:00 PM ET",
    format: "Live webinar",
    relevance: "high",
    description: "Session on patentability triage decisions in an era of AI-assisted invention and drafting.",
    tags: ["AI Drafting", "Patentability"],
    url: "https://ipwatchdog.com/event/webinar-ip-com-2026-09-03-before-the-draft/",
  },
  {
    id: "wb-7",
    title: "AI in Patent Practice — Change Management for Successful Adoption",
    host: "Ankar AI",
    date: "2026-09-10",
    time: "12:00 PM ET",
    format: "Live webinar",
    relevance: "high",
    description:
      "Direct Tier 1 competitor-hosted session on change management for AI adoption in patent prosecution and portfolio workflows.",
    tags: ["Competitor-hosted", "AI Adoption"],
    url: "https://ipwatchdog.com/ankar-ai-september-10-2026/",
  },
  {
    id: "wb-8",
    title: "AI & IP USA",
    host: "WIPR / Newton Media",
    date: "2026-10-06",
    time: "In-person, New York",
    format: "Conference",
    relevance: "medium",
    description: "Two-day industry conference on AI's impact across IP strategy, prosecution, and enforcement.",
    tags: ["Conference", "Industry Event"],
    url: "https://events.newton.media/AI-and-IP-USA/home",
  },
];

// Expose to the rest of the app
window.PATLYTICS_DATA = {
  ANCHOR_DATE,
  EARLIEST_DATE,
  HIGHLIGHTS,
  COMPETITORS,
  NEW_ENTRANTS,
  WEBINARS,
};
